config/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import redirect_index

urlpatterns = [
    path('', redirect_index),
    path('hrdb/', include('hrdb.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

hrdb/urls.py
from django.urls import path

from . import views

app_name = 'hrdb'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='index'),
    path('companies/', views.CompanyListView.as_view(), name='companies'),
    path('company/new/',
         views.CompanyCreateView.as_view(),
         name='company_new'),
    path('company/<int:pk>/edit/',
         views.CompanyUpdateView.as_view(),
         name='company_edit'),
    path('company/<int:pk>/delete/',
         views.CompanyDeleteView.as_view(),
         name='company_delete'),
    path('educationestablishments/',
         views.EducationEstablishmentListView.as_view(),
         name='educationestablishments'),
    path('educationestablishment/new/',
         views.EducationEstablishmentCreateView.as_view(),
         name='educationestablishment_new'),
    path('educationestablishment/<int:pk>/edit/',
         views.EducationEstablishmentUpdateView.as_view(),
         name='educationestablishment_edit'),
    path('educationestablishment/<int:pk>/delete/',
         views.EducationEstablishmentDeleteView.as_view(),
         name='educationestablishment_delete'),
    path('orgstructure/',
         views.OrgStructureListView.as_view(),
         name='orgstructure'),
    path('orgstructure/new/',
         views.OrgStructureCreateView.as_view(),
         name='orgstructure_new'),
    path('orgstructure/<int:pk>/edit/',
         views.OrgStructureUpdateView.as_view(),
         name='orgstructure_edit'),
    path('officeseekers/',
         views.OfficeSeekerListView.as_view(),
         name='officeseekers'),
    path('officeseekers/<int:pk>',
         views.OfficeSeekerDetailView.as_view(),
         name='officeseeker_detail'),
    path('officeseekers/new/',
         views.OfficeSeekerCreateView.as_view(),
         name='officeseeker_new'),
    path('officeseekers/<int:pk>/edit/',
         views.OfficeSeekerUpdateView.as_view(),
         name='officeseeker_edit'),
    path('personemail/<int:person_id>/add/',
         views.person_email_create,
         name='personemail_add'),
    path('personemail/<int:person_id>/edit/<int:email_id>',
         views.person_email_edit,
         name='personemail_edit'),
    path('personphone/<int:person_id>/add/',
         views.person_phone_create,
         name='personphone_add'),
    path('personphone/<int:person_id>/edit/<int:phone_id>',
         views.person_phone_edit,
         name='personphone_edit'),
    path('personeducational/<int:person_id>/add/',
         views.person_educational_create,
         name='personeducational_add')
]

hrdb/models.py
from django.db import models
from django.shortcuts import reverse


class Company(models.Model):
    c_full_name = models.CharField(max_length=255,
                                   db_index=True,
                                   verbose_name='Полное название')
    c_short_name = models.CharField(max_length=32,
                                    db_index=True,
                                    verbose_name='Краткое название')

    def __str__(self):
        return self.c_short_name

    class Meta:
        ordering = ['c_short_name']
        unique_together = ('c_short_name', 'c_full_name')


class EducationEstablishment(models.Model):
    e_full_name = models.CharField(max_length=255,
                                   db_index=True,
                                   verbose_name='Полное название')
    e_short_name = models.CharField(max_length=32,
                                    db_index=True,
                                    verbose_name='Краткое название')

    def __str__(self):
        return f'{self.e_short_name} | {self.e_full_name}'

    class Meta:
        ordering = ['e_short_name']
        unique_together = ('e_short_name', 'e_full_name')


class OrganizationStructure(models.Model):
    organizational_unit = models.CharField(
        max_length=255,
        db_index=True,
        verbose_name='Структурное подразделение'
    )
    parent_ou_id = models.ForeignKey(to='OrganizationStructure',
                                     on_delete=models.CASCADE,
                                     null=True, blank=True,
                                     verbose_name='Вышестоящее подразделение')
    company_id = models.ForeignKey(Company,
                                   on_delete=models.CASCADE,
                                   verbose_name='Компания')

    def __str__(self):
        return self.organizational_unit


class Person(models.Model):
    WOMAN = 0
    MAN = 1
    SEX = (
        (WOMAN, 'женский'),
        (MAN, 'мужской')
    )

    last_name = models.CharField(max_length=64, db_index=True,
                                 verbose_name='Фамилия')
    first_name = models.CharField(max_length=64, db_index=True,
                                  verbose_name='Имя')
    middle_name = models.CharField(max_length=64, blank=True,
                                   verbose_name='Отчество')
    sex = models.IntegerField(choices=SEX, verbose_name='Пол')
    birth_date = models.DateField(verbose_name='Дата рождения')
    address = models.CharField(max_length=255,
                               blank=True,
                               verbose_name='Адрес')

    def __str__(self):
        return '{} {}'.format(self.last_name, self.first_name)

    def get_full_name(self):
        return '{} {} {}'.format(self.last_name, self.first_name,
                                 self.middle_name)

    def get_absolute_url(self):
        return reverse('hrdb:officeseeker_detail', kwargs={'pk': self.id})


class OfficeSeeker(Person, models.Model):
    NOT_MEETING = 0
    GOOD_FOR = 1
    EXCLUDE = 2
    RESERVE = 3
    EMPLOYED = 4
    STATUS = (
        (NOT_MEETING, 'не собеседовался'),
        (GOOD_FOR, 'подходит'),
        (EXCLUDE, 'исключить'),
        (RESERVE, 'резерв'),
        (EMPLOYED, 'принят на работу'),
    )
    INSIDE = 0
    WORK_UA = 1
    HH = 2
    _0629 = 3
    OLX = 4
    RABOTA_UA = 5
    SOURCE = (
        (INSIDE, 'внутренний'),
        (WORK_UA, 'work.ua'),
        (HH, 'headHunter'),
        (_0629, '0629'),
        (OLX, 'olx'),
        (RABOTA_UA, 'rabota.ua'),
    )

    status = models.IntegerField(choices=STATUS, default=NOT_MEETING,
                                 verbose_name='Статус')
    source = models.IntegerField(choices=SOURCE, default=INSIDE,
                                 verbose_name='Источник')


class PersonsEmail(models.Model):
    email = models.EmailField(verbose_name='eMail', blank=False)
    person_id = models.ForeignKey(Person, on_delete=models.CASCADE,
                                  verbose_name='Ф.И.О.',
                                  related_name='personemails')

    def __str__(self):
        return '{} - {}'.format(self.email, self.person_id)


class PersonPhone(models.Model):
    phone = models.CharField(max_length=20,
                             blank=False,
                             verbose_name='Телефон')
    person = models.ForeignKey(Person, on_delete=models.CASCADE,
                               verbose_name='Ф.И.О.',
                               related_name='personphones')

    def __str__(self):
        return '{}: {}'.format(self.phone, self.person)


class Educational(models.Model):
    QUALIFICATION = [
        (1, 'среднее'),
        (2, 'среднее специальное'),
        (3, 'неоконченное высшее'),
        (4, 'высшее'),
    ]
    person = models.ForeignKey(Person,
                               on_delete=models.CASCADE,
                               verbose_name='Ф.И.О.',
                               related_name='person_edicational')
    education_establishment = models.ForeignKey(
            EducationEstablishment,
            on_delete=models.CASCADE,
            verbose_name='Учебное заведение',
            related_name='person_edu')
    year_graduated = models.PositiveSmallIntegerField(
            verbose_name='Год окончания', blank=True, null=True)
    profession = models.CharField(max_length=255, verbose_name='Специальность')
    qualification = models.PositiveSmallIntegerField(
            choices=QUALIFICATION,
            default=1,
            verbose_name='Квалификация')

hrdb/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import CompanyForm, EducationEstablishmentForm, OrgStructureForm, \
    OfficeSeekerForm, PersonEmailForm, PersonPhoneForm, PersonEducationalForm
from .models import Company, EducationEstablishment, OrganizationStructure, \
    Person, OfficeSeeker, PersonsEmail, PersonPhone, Educational


class HomePageView(TemplateView):
    template_name = 'hrdb/index.html'


# Компании группы "МИГ"
class CompanyListView(LoginRequiredMixin, ListView):
    model = Company
    template_name = 'hrdb/company_list.html'


class CompanyCreateView(LoginRequiredMixin, CreateView):
    form_class = CompanyForm
    template_name = 'hrdb/company_create.html'
    success_url = reverse_lazy('hrdb:companies')


class CompanyUpdateView(LoginRequiredMixin, UpdateView):
    model = Company
    form_class = CompanyForm
    template_name = 'hrdb/company_edit.html'
    success_url = reverse_lazy('hrdb:companies')


class CompanyDeleteView(LoginRequiredMixin, DeleteView):
    model = Company
    template_name = 'hrdb/company_delete.html'
    success_url = reverse_lazy('hrdb:companies')


# Учебные заведения
class EducationEstablishmentListView(LoginRequiredMixin, ListView):
    model = EducationEstablishment
    template_name = 'hrdb/EducationEstablishment_list.html'


class EducationEstablishmentCreateView(LoginRequiredMixin, CreateView):
    form_class = EducationEstablishmentForm
    template_name = 'hrdb/EducationEstablishment_create.html'
    success_url = reverse_lazy('hrdb:educationestablishments')


class EducationEstablishmentUpdateView(LoginRequiredMixin, UpdateView):
    model = EducationEstablishment
    form_class = EducationEstablishmentForm
    template_name = 'hrdb/EducationEstablishment_edit.html'
    success_url = reverse_lazy('hrdb:educationestablishments')


class EducationEstablishmentDeleteView(LoginRequiredMixin, DeleteView):
    model = EducationEstablishment
    template_name = 'hrdb/EducationEstablishment_delete.html'
    success_url = reverse_lazy('hrdb:educationestablishments')


# Оргструктура
class OrgStructureListView(LoginRequiredMixin, ListView):
    model = OrganizationStructure
    template_name = 'hrdb/organizationstructure_list.html'


class OrgStructureCreateView(LoginRequiredMixin, CreateView):
    form_class = OrgStructureForm
    template_name = 'hrdb/organizationstructure_create.html'
    success_url = reverse_lazy('hrdb:orgstructure')


class OrgStructureUpdateView(LoginRequiredMixin, UpdateView):
    model = OrganizationStructure
    form_class = OrgStructureForm
    template_name = 'hrdb/organizationstructure_update.html'
    success_url = reverse_lazy('hrdb:orgstructure')


# Соискатели/Персонал
class OfficeSeekerListView(LoginRequiredMixin, ListView):
    model = OfficeSeeker
    template_name = 'hrdb/officeseeker_list.html'


class OfficeSeekerDetailView(LoginRequiredMixin, DetailView):
    model = OfficeSeeker
    template_name = 'hrdb/officeseeker_detail.html'


class OfficeSeekerCreateView(LoginRequiredMixin, CreateView):
    form_class = OfficeSeekerForm
    template_name = 'hrdb/officeseeker_new.html'
    success_url = reverse_lazy('hrdb:officeseekers')


class OfficeSeekerUpdateView(LoginRequiredMixin, UpdateView):
    model = OfficeSeeker
    form_class = OfficeSeekerForm
    template_name = 'hrdb/officeseeker_new.html'
    success_url = reverse_lazy('hrdb:officeseekers')


def person_email_create(request, person_id):
    if request.method == 'POST':
        PersonsEmail.objects.create(
            email=request.POST['email'],
            person_id=Person.objects.get(id=request.POST['person_id'])
        )
        return redirect('hrdb:officeseeker_detail', pk=person_id)
    else:
        person = Person.objects.get(id=person_id)
        form = PersonEmailForm(initial={'person_id': person_id})
        return render(request, 'hrdb/person_email.html', {'form': form,
                                                          'person': person})


def person_email_edit(request, person_id, email_id):
    if request.method == 'POST':
        person_email = PersonsEmail.objects.get(id=email_id)
        person_email.email = request.POST['email']
        person_email.save()
        return redirect('hrdb:officeseeker_detail', pk=person_id)
    else:
        person = Person.objects.get(id=person_id)
        email = PersonsEmail.objects.get(id=email_id)
        form = PersonEmailForm(initial={'person_id': person_id,
                                        'email': email.email})
        context = {'form': form, 'person': person, 'email': email.email}
        return render(request, 'hrdb/person_email.html', context)


def person_phone_create(request, person_id):
    if request.method == 'POST':
        PersonPhone.objects.create(
            phone=request.POST['phone'],
            person=Person.objects.get(id=request.POST['person'])
        )
        return redirect('hrdb:officeseeker_detail', pk=person_id)
    else:
        person = Person.objects.get(id=person_id)
        form = PersonPhoneForm(initial={'person': person_id})
        return render(request, 'hrdb/person_phone.html', {'form': form,
                                                          'person': person})


def person_phone_edit(request, person_id, phone_id):
    if request.method == 'POST':
        person_phone = PersonPhone.objects.get(id=phone_id)
        person_phone.phone = request.POST['phone']
        person_phone.save()
        return redirect('hrdb:officeseeker_detail', pk=person_id)
    else:
        person = Person.objects.get(id=person_id)
        phone = PersonPhone.objects.get(id=phone_id)
        form = PersonPhoneForm(initial={'person_id': person.id,
                                        'phone': phone.id})
        context = {'form': form, 'person': person, 'phone': phone.phone}
        return render(request, 'hrdb/person_phone.html', context)


def person_educational_create(request, person_id):
    if request.method == 'POST':
        Educational.objects.create(
            person=Person.objects.get(id=request.POST['person']),
            education_establishment=EducationEstablishment.objects.get(
                id=request.POST['education_establishment']),
            profession=request.POST['profession'],
            qualification=request.POST['qualification']
        )
        return redirect('hrdb:officeseeker_detail', pk=person_id)
    else:
        person = Person.objects.get(id=person_id)
        form = PersonEducationalForm(initial={'person': person.id})
        return render(request, 'hrdb/person_educational.html',
                      {'form': form, 'person': person})

hrdb/templates/hrdb/EducationEstablishment_delete.html
{% extends "base.html" %}

{% block title %}
  Удалить учебное заведение - {{ block.super }}
{% endblock %}

{% block content %}
  <form method="post">
    {% csrf_token %}

    <h3>Вы действительно хотите удалить учебное заведение <b>"{{ educationestablishment.e_full_name }}"</b> из справочника?</h3>
    <a href="{% url 'hrdb:educationestablishments' %}" class="btn btn-primary"><span class="icon icon-reply"></span> Назад</a>
    <button type="submit" name="button" class="btn btn-danger"><span class="icon icon-trash"></span> Удалить</button>

  </form>
{% endblock %}

hrdb/templates/hrdb/EducationEstablishment_edit.html
{% extends "base.html" %}

{% block title %}
  Редактировать учебное заведение - {{ block.super }}
{% endblock %}

{% block content %}

  <h3>Изменить информацию об учебном заведении</h3>

  <form method="post" class="">
    {% csrf_token %}

    {% for field in form %}
      <div class="form-group">
        {% if field.errors %}
          <div class="alert alert-danger">
              {{ field.errors }}
          </div>
        {% endif %}

        {{ field.label }}
        {{ field }}
      </div>
    {% endfor %}
    <div class="row justify-content-between btn-row">
      <button type="submit" class="btn btn-primary">
        <span class="icon icon-floppy"></span>
        Сохранить</button>
      <a href="{% url 'hrdb:educationestablishment_delete' educationestablishment.id %}" class="btn btn-danger">
        <span class="icon icon-trash"></span>
        Удалить учебное заведение</a>
    </div>
  </form>

  <br>
  <p><a href="{% url 'hrdb:educationestablishments' %}">
      <span class="icon icon-reply"></span>
      Назад к списку учебных заведений</a></p>

{% endblock %}

hrdb/templates/hrdb/EducationEstablishment_list.html
{% extends "base.html" %}

{% block title %}
  Учебные заведения - {{ block.super }}
{% endblock %}

{% block content %}
  <p><a href="{% url 'hrdb:educationestablishment_new' %}">Добавить новое учебное заведение</a></p>
  <table class="table table-sm table-hover">
    <thead class="thead-dark">
      <tr>
        <th></th>
        <th scope="col">Краткое название</th>
        <th scope="col">Полное название учебного заведния</th>
      </tr>
    </thead>
    <tbody>
    {% for educationestablishment in educationestablishment_list %}
      <tr>
        <td>
          <a href="{% url 'hrdb:educationestablishment_edit' educationestablishment.id %}">
            <span class="icon icon-pencil"></span></a></td>
        <td>{{ educationestablishment.e_short_name }}</td>
        <td>{{ educationestablishment.e_full_name }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock %}

hrdb/templates/hrdb/company_create.html
{% extends "base.html" %}

{% block title %}
  Новая компания - {{ block.super }}
{% endblock %}

{% block content %}

  <h3>Новая компания</h3>

  <form method="post" class="">
    {% csrf_token %}

    {% for field in form %}
      <div class="form-group">
        {% if field.errors %}
          <div class="alert alert-danger">
              {{ field.errors }}
          </div>
        {% endif %}

        {{ field.label }}
        {{ field }}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">
      <span class="icon icon-floppy"></span>
      Сохранить</button>
  </form>
  <br>
  <p><a href="{% url 'hrdb:companies' %}"><span class="icon icon-reply"></span> Назад к списку компаний</a></p>

{% endblock %}

hrdb/templates/hrdb/company_delete.html
{% extends "base.html" %}

{% block title %}
  Удалить компанию - {{ block.super }}
{% endblock %}

{% block content %}
  <form method="post">
    {% csrf_token %}

    <h3>Вы действительно хотите удалить компанию <b>"{{ company.c_full_name }}"</b> из справочника?</h3>
    <a href="{% url 'hrdb:companies' %}" class="btn btn-primary"><span class="icon icon-reply"></span> Назад</a>
    <button type="submit" name="button" class="btn btn-danger"><span class="icon icon-trash"></span> Удалить</button>

  </form>
{% endblock %}

hrdb/templates/hrdb/company_edit.html
{% extends "base.html" %}

{% block title %}
  Редактировать компанию - {{ block.super }}
{% endblock %}

{% block content %}

  <h3>Редактировать информацию о компании</h3>

  <form method="post" class="">
    {% csrf_token %}
    {% for field in form %}
      <div class="form-group">
        {% if field.errors %}
          <div class="alert alert-danger">
              {{ field.errors }}
          </div>
        {% endif %}
          {{ field.label }}
          {{ field }}
      </div>
    {% endfor %}
    <div class="row justify-content-between btn-row">
        <button type="submit" class="btn btn-primary">
          <span class="icon icon-floppy"></span>
          Сохранить</button>
        <a href="{% url 'hrdb:company_delete' company.id %}" class="btn btn-danger">
          <span class="icon icon-trash"></span>
          Удалить компанию</a>
    </div>
  </form>
  <br>
  <p><a href="{% url 'hrdb:companies' %}"><span class="icon icon-reply"></span> Назад к списку компаний</a></p>

{% endblock %}

hrdb/templates/hrdb/company_list.html
{% extends "base.html" %}

{% block title %}
  Компании группы "МИГ" - {{ block.super }}
{% endblock %}

{% block content %}
  <p><a href="{% url 'hrdb:company_new' %}">
    <span class="icon icon-plus"></span>
    Добавить новую компанию</a></p>
  <table class="table table-sm table-hover">
    <thead class="thead-dark">
      <tr>
        <th></th>
        <th scope="col">Краткое название</th>
        <th scope="col">Полное название компании</th>
      </tr>
    </thead>
    <tbody>
    {% for company in company_list %}
      <tr>
        <td>
          <a href="{% url 'hrdb:company_edit' company.id %}">
            <span class="icon icon-pencil"></span></a></td>
        <td>{{ company.c_short_name }}</td>
        <td>{{ company.c_full_name }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock %}

hrdb/templates/hrdb/officeseeker_detail.html
{% extends "base.html" %}

{% block title %}
  Cоискатель - {{ block.super }}
{% endblock %}

{% block content %}
<div class="container col-sm-6 col-md-10">
  <div class="row">
    <div class="card mr-1" style="width: 29rem;">
      <div class="card-header
              {% if object.status == 0 %}
                alert-secondary
              {% elif object.status == 1 %}
                alert-success
              {% elif object.status == 2 %}
                alert-light
              {% elif object.status == 3 %}
                alert-primary
              {% else %}
                alert-warning
              {% endif %}
            ">
        <h4>{{ object.last_name }} {{ object.first_name }} {{ object.middle_name }}</h4>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <div class="row">
            <div class="col-5" style="text-align: right">
              <b>Дата рождения:</b>
            </div>
            <div class="col-7">
              {{ object.birth_date|date:"d.m.Y" }}
            </div>
          </div>
        </li>
        <li class="list-group-item">
          <div class="row">
            <div class="col-5" style="text-align: right">
              <b>Пол:</b>
            </div>
            <div class="col-7">
              {{ object.get_sex_display }}
            </div>
          </div>
        </li>
        <li class="list-group-item">
          <div class="row">
            <div class="col-5" style="text-align: right">
              <b>Адрес:</b>
            </div>
            <div class="col-7">
              {{ object.address }}
            </div>
          </div>
        </li>
        <li class="list-group-item">
          <div class="row">
            <div class="col-5" style="text-align: right">
              <b>Источник поиска:</b>
            </div>
            <div class="col-7">
              {{ object.get_source_display }}
            </div>
          </div>
        </li>
        <li class="list-group-item">
          <div class="row">
            <div class="col-5" style="text-align: right">
              <b>Статус:</b>
            </div>
            <div class="col-7">
              {{ object.get_status_display }}
            </div>
          </div>
        </li>
        <li class="list-group-item">
          <div class="row">
            <div class="col-5" style="text-align: right">
              <b>eMail:</b>&nbsp;
              <a href="{% url 'hrdb:personemail_add' object.id %}">
                <span class="icon icon-plus-squared green"></span></a>
            </div>
            <div class="col-7">
              {% for personemail in officeseeker.personemails.all %}
                <a href="{% url 'hrdb:personemail_edit' officeseeker.id personemail.id %}">
                  <span class="icon icon-pencil"></span></a>
                {{ personemail.email }};<br>
              {% endfor %}
            </div>
          </div>
        </li>
        <li class="list-group-item">
          <div class="row">
            <div class="col-5" style="text-align: right">
              <b>Телефон:</b>&nbsp;
              <a href="{% url 'hrdb:personphone_add' object.id %}">
                <span class="icon icon-plus-squared green"></span></a>
            </div>
            <div class="col-7">
              {% for personphone in officeseeker.personphones.all %}
                <a href="{% url 'hrdb:personphone_edit' officeseeker.id personphone.id %}">
                  <span class="icon icon-pencil"></span></a>
                {{ personphone.phone }};<br>
              {% endfor %}
            </div>
          </div>
        </li>
      </ul>
    </div>
    <div class="card" style="width: 29rem;">
      <div class="card-header">
        <h4>Образование
        <a href="{% url 'hrdb:personeducational_add' object.id %}">
          <span class="icon icon-plus-squared green"></span></a></h4>
      </div>
      <ul class="list-group list-group-flush">
        {% for person_edu in officeseeker.person_edicational.all %}
          <li class="list-group-item">
            <h5>{{ person_edu.education_establishment.e_full_name }}
              ({{ person_edu.education_establishment.e_short_name }})
              [{{ person_edu.year_graduated|default:"N/A" }}]
            </h5>
            <b>Специальность:</b> {{ person_edu.profession }}<br>
            <b>Квалификация:</b> {{ person_edu.get_qualification_display }}
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
  <br>
    <p class="btn-group" role="group" >
      <a href="{% url 'hrdb:officeseekers' %}" class="btn btn-sm btn-info">
              <span class="icon icon-reply"></span> Назад</a>
      <a href="{% url 'hrdb:officeseeker_edit' object.id %}" class="btn btn-sm btn-primary">
              <span class="icon icon-pencil"></span> Редактировать</a>
    </p>
</div>
{% endblock %}

hrdb/templates/hrdb/officeseeker_new.html
{% extends "base.html" %}

{% block title %}
  Добавить соискателя - {{ block.super }}
{% endblock %}

{% block content %}

  <div class="container col-6">
    <h3>Добавить соискателя</h3>

    <form method="post" class="">
      {% csrf_token %}

      {% for field in form %}
        <div class="form-group">
          {% if field.errors %}
            <div class="alert alert-danger">
                {{ field.errors }}
            </div>
          {% endif %}

          {{ field.label }}
          {{ field }}
        </div>
      {% endfor %}
      <button type="submit" class="btn btn-primary">
        <span class="icon icon-floppy"></span>
        Сохранить</button>
    </form>
    <br>
    <p><a href="{% url 'hrdb:officeseekers' %}">
      <span class="icon icon-reply"></span> Назад к списку соискателей</a></p>
  </div>
{% endblock %}

hrdb/templates/hrdb/organizationstructure_create.html
{% extends "base.html" %}

{% block title %}
  Новое структурное подразделение - {{ block.super }}
{% endblock %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-6">

    <h3>Новое структурное подразделение</h3>

    <form method="post" class="">
      {% csrf_token %}

      {% for field in form %}
        <div class="form-group">
          {% if field.errors %}
            <div class="alert alert-danger">
                {{ field.errors }}
            </div>
          {% endif %}

          {{ field.label }}
          {{ field }}
        </div>
      {% endfor %}
      <button type="submit" class="btn btn-primary">
        <span class="icon icon-floppy"></span>
        Сохранить</button>
    </form>
    <br>
    <p>
      <a href="{% url 'hrdb:orgstructure' %}">
        <span class="icon icon-reply"></span>
        Назад к оргструктуре
      </a>
    </p>
  </div>
</div>
{% endblock %}

hrdb/templates/hrdb/organizationstructure_list.html
{% extends "base.html" %}

{% block title %}
  Организационная структура - {{ block.super }}
{% endblock %}

{% block content %}
  <p><a href="{% url 'hrdb:orgstructure_new' %}">Добавить подразделение</a></p>
  <table class="table table-sm table-hover">
    <thead class="thead-dark">
      <tr>
        <th></th>
        <th scope="col">Компания</th>
        <th scope="col">Подразделение</th>
        <th scope="col">Вышестоящее подразделение</th>
      </tr>
    </thead>
    <tbody>
    {% for orgunit in organizationstructure_list %}
      <tr>
        <td>
          <a href="{% url 'hrdb:orgstructure_edit' orgunit.id %}">
            <span class="icon icon-pencil"></span></a></td>
        <td>{{ orgunit.company_id }}</td>
        <td>{{ orgunit.organizational_unit }}</td>
        <td>{{ orgunit.parent_ou_id|default:"" }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock %}