config/urls.py
from django.contrib import admin
from django.urls import path, include

from .views import redirect_index

urlpatterns = [
    path('', redirect_index),
    path('hrdb/', include('hrdb.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

hrdb/urls.py
from django.urls import path

from . import views

app_name = 'hrdb'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='index'),
    path('companies/', views.CompanyListView.as_view(), name='companies'),
    path('company/new/',
         views.CompanyCreateView.as_view(),
         name='company_new'),
    path('company/<int:pk>/edit/',
         views.CompanyUpdateView.as_view(),
         name='company_edit'),
    path('company/<int:pk>/delete/',
         views.CompanyDeleteView.as_view(),
         name='company_delete'),
    path('educationestablishments/',
         views.EducationEstablishmentListView.as_view(),
         name='educationestablishments'),
    path('educationestablishment/new/',
         views.EducationEstablishmentCreateView.as_view(),
         name='educationestablishment_new'),
    path('educationestablishment/<int:pk>/edit/',
         views.EducationEstablishmentUpdateView.as_view(),
         name='educationestablishment_edit'),
    path('educationestablishment/<int:pk>/delete/',
         views.EducationEstablishmentDeleteView.as_view(),
         name='educationestablishment_delete'),
    path('orgstructure/',
         views.OrgStructureListView.as_view(),
         name='orgstructure'),
    path('orgstructure/new/',
         views.OrgStructureCreateView.as_view(),
         name='orgstructure_new'),
    path('orgstructure/<int:pk>/edit/',
         views.OrgStructureUpdateView.as_view(),
         name='orgstructure_edit'),
    path('officeseekers/',
         views.OfficeSeekerListView.as_view(),
         name='officeseekers'),
    path('officeseekers/<int:pk>',
         views.OfficeSeekerDetailView.as_view(),
         name='officeseeker_detail'),
    path('officeseekers/new/',
         views.OfficeSeekerCreateView.as_view(),
         name='officeseeker_new'),
    path('officeseekers/<int:pk>/edit/',
         views.OfficeSeekerUpdateView.as_view(),
         name='officeseeker_edit'),
    path('personemail/<int:person_id>/add/',
         views.person_email_create,
         name='personemail_add'),
    path('personemail/<int:person_id>/edit/<int:email_id>',
         views.person_email_edit,
         name='personemail_edit'),
    path('personphone/<int:person_id>/add/',
         views.person_phone_create,
         name='personphone_add'),
    path('personphone/<int:person_id>/edit/<int:phone_id>',
         views.person_phone_edit,
         name='personphone_edit'),
    path('personeducational/<int:person_id>/add/',
         views.person_educational_create,
         name='personeducational_add')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/photon-icon.css' %}">
    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <title>
        {% block title %}
            HRDB
        {% endblock %}
    </title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #555;">
      <a class="navbar-brand" href="{% url 'hrdb:index' %}">HRDB</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Отчёты</a>
          </li>
        </ul>

        <div class="dropdown mr-2">
          <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            "Резюме"
          </a>

          <div class="dropdown-menu  dropdown-menu-right" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item" href="{% url 'hrdb:officeseekers' %}">
              <span class="icon icon-users"></span>
              Соискатели</a>
          </div>
        </div>

        <div class="dropdown mr-2">
          <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Справочники
          </a>

          <div class="dropdown-menu  dropdown-menu-right" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item" href="{% url 'hrdb:companies' %}">Компании группы "МИГ"</a>
            <a class="dropdown-item" href="{% url 'hrdb:orgstructure' %}">Организационная структура</a>
            <a class="dropdown-item" href="{% url 'hrdb:educationestablishments' %}">Учебные заведения</a>
          </div>
        </div>
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            {% if user.is_authenticated %}
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="icon icon-user"></span>
              {{ user.username }}
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="/admin/"><span class="icon icon-cog"></span> Админка</a>
              <a class="dropdown-item" href="{% url 'signup' %}">
                <span class="icon icon-user-add"></span>
                Зарегистрировать пользователя</a>
              <a class="dropdown-item" href="{% url 'logout' %}"><span class="icon icon-logout"></span> Выйти</a>
            </div>
            {% else %}
              <a href="{% url 'login' %}"><span class="icon icon-login"></span> login</a>
            {% endif %}
          </li>
        </ul>
      </div>
    </nav>

    <div class="container col-12 mt-3">
      <div class="row justify-content-center">
        <div class="container col-12">
          {% block content %}
            There is no any content for you
          {% endblock %}
        </div>
      </div>
    </div>
</body>
</html>